#server:
#  port: 10086 #服务端口
#spring:
#  application:
#    name: eureka-server  # eureka服务名称
#eureka:
#  client:
#    service-url:  #eureka地址信息
#      defaultZone: http://127.0.0.1:10086/eureka
server:
  port: 10086
spring:
  application:
    name: eurekaserver
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
ribbon:
  eager-load:
    enabled: true #开启饥饿加载
    clients: userservice  #指定饥饿加载的服务